language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5-dev
      env: TOXENV=py35

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev

install:
  - pip install -U tox

script:
  - tox
